site_name: IKIM Cluster
site_url: https://ikim-essen.github.io/ClusterDocs/
copyright: Copyright &copy; 2023 Institut für künstliche Intelligenz in der Medizin (IKIM), Essen

theme:
  name: material
  features:
    - navigation.sections

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Introduction: index.md
  - Available Resources: resources.md
  - Requesting Access: access.md
  - Connecting:
     - Setting up SSH: ssh-setup.md
     - First steps: first-steps.md
  - Setup:
     - Mamba/Conda: conda.md
     - Containers: apptainer.md
     - Jupyter Notebooks: jupyter.md
     - VS Code: vs-code-setup.md
  - Data:
     - Storage: storage.md
     - Transfer: transfer.md
     - Accessing Cluster storage: accessing-storage.md
  - Computing: 
     - Snakemake: snakemake.md
     - Slurm: slurm.md
  - Misc:
     - Troubleshooting: troubleshooting.md
     - Patterns: patterns.md
