site_name: IKIM Cluster
copyright: Copyright &copy; 2021 Institut für künstliche Intelligenz in der Medizin (IKIM), Essen

theme:
  name: material
  features:
    - navigation.sections

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - User Guide:
     - Docker: docker.md
     - Jupyter Notebooks: jupyter.md
     - Troubleshooting: troubleshooting.md
